services:
  - type: web
    name: diabetes-fastapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand:  uvicorn diabetes_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
